package domain

import "errors"

var (
	ErrAccountIDInvalid               = errors.New("identity: account id is invalid")
	ErrLoginNameInvalid               = errors.New("identity: login name is invalid")
	ErrPrincipalIDInvalid             = errors.New("identity: principal id is invalid")
	ErrSessionRefInvalid              = errors.New("identity: session reference is invalid")
	ErrOperationRefInvalid            = errors.New("identity: operation reference is invalid")
	ErrAccountStatusUnsupported       = errors.New("identity: account status is unsupported")
	ErrCredentialVersionInvalid       = errors.New("identity: credential version is invalid")
	ErrAuthenticationEpochInvalid     = errors.New("identity: authentication epoch is invalid")
	ErrAccountTimeInvalid             = errors.New("identity: account time is invalid")
	ErrPasswordEnvelopeInvalid        = errors.New("identity: password envelope is invalid")
	ErrWorkforceAccountInvalid        = errors.New("identity: workforce account is invalid")
	ErrTokenDigestInvalid             = errors.New("identity: token digest is invalid")
	ErrSessionInvalid                 = errors.New("identity: session is invalid")
	ErrSessionTimeInvalid             = errors.New("identity: session time is invalid")
	ErrSessionEvaluationTimeInvalid   = errors.New("identity: session evaluation time is invalid")
	ErrSessionRevokeReasonUnsupported = errors.New("identity: session revoke reason is unsupported")
	ErrSessionRevocationInvalid       = errors.New("identity: session revocation is invalid")
	ErrSessionAlreadyRevoked          = errors.New("identity: session is already revoked")
	ErrSessionTouchInvalid            = errors.New("identity: session touch is invalid")
	ErrSessionInactive                = errors.New("identity: session is inactive")
	ErrThrottleDimensionUnsupported   = errors.New("identity: throttle dimension is unsupported")
	ErrThrottleDigestInvalid          = errors.New("identity: throttle digest is invalid")
	ErrAdmissionEpochInvalid          = errors.New("identity: admission epoch is invalid")
	ErrAdmissionEpochExhausted        = errors.New("identity: admission epoch is exhausted")
	ErrThrottleStateInvalid           = errors.New("identity: throttle state is invalid")
	ErrThrottleCountInvalid           = errors.New("identity: throttle count is invalid")
	ErrThrottleTimeInvalid            = errors.New("identity: throttle time is invalid")
	ErrThrottleEvaluationTimeInvalid  = errors.New("identity: throttle evaluation time is invalid")
)
